import { NextResponse } from "next/server";
import { Resend } from "resend";
import { contactSchema } from "@/lib/contact";

export async function POST(request: Request) {
  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json(
      { ok: false, message: "Please check your form and try again." },
      { status: 400 },
    );
  }

  const result = contactSchema.safeParse(body);
  if (!result.success) {
    return NextResponse.json(
      { ok: false, message: "Please complete every field with valid details." },
      { status: 400 },
    );
  }

  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) {
    return NextResponse.json(
      {
        ok: false,
        message:
          "Message delivery is temporarily unavailable. Please email me directly.",
      },
      { status: 503 },
    );
  }

  try {
    const resend = new Resend(apiKey);
    const { error } = await resend.emails.send({
      from:
        process.env.CONTACT_FROM_EMAIL ||
        "JPTECH Portfolio <onboarding@resend.dev>",
      to: "josephchukwuka4@gmail.com",
      replyTo: result.data.email,
      subject: `💼 Portfolio Enquiry from ${result.data.name}`,
      html: `
    <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 8px; background-color: #fdfdfd;">
      <h2 style="color: #1a1a1a; border-bottom: 2px solid #4f46e5; padding-bottom: 10px; margin-top: 0;">
        New Contact Form Submission
      </h2>
      
      <p style="font-size: 16px; color: #555; margin: 15px 0;">
        You have received a new inquiry from your <strong>JPTECH Portfolio</strong> website.
      </p>

      <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
        <tr>
          <td style="padding: 10px; background-color: #f3f4f6; font-weight: bold; width: 30%; border-radius: 4px 0 0 4px; color: #4b5563;">Name:</td>
          <td style="padding: 10px; background-color: #f9fafb; border-radius: 0 4px 4px 0; color: #111827;">${result.data.name}</td>
        </tr>
        <tr>
          <td style="padding: 10px; background-color: #f3f4f6; font-weight: bold; border-radius: 4px 0 0 4px; color: #4b5563; padding-top: 15px;">Email:</td>
          <td style="padding: 10px; background-color: #f9fafb; border-radius: 0 4px 4px 0; color: #4f46e5; padding-top: 15px;">
            <a href="mailto:${result.data.email}" style="color: #4f46e5; text-decoration: none;">${result.data.email}</a>
          </td>
        </tr>
      </table>

      <div style="margin-top: 25px;">
        <h3 style="color: #374151; font-size: 14px; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 10px;">Message:</h3>
        <div style="padding: 15px; background-color: #f9fafb; border-left: 4px solid #4f46e5; border-radius: 4px; color: #1f2937; line-height: 1.6; white-space: pre-wrap;">
          ${result.data.message}
        </div>
      </div>

      <footer style="margin-top: 40px; padding-top: 15px; border-top: 1px solid #e5e7eb; text-align: center; font-size: 12px; color: #9ca3af;">
        This email was automatically generated by your JPTECH Portfolio.
      </footer>
    </div>
  `,
    });

    if (error) throw error;
    return NextResponse.json({ ok: true });
  } catch {
    return NextResponse.json(
      { ok: false, message: "Delivery failed. Please email me directly." },
      { status: 502 },
    );
  }
}
